# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xbuf/cmds.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import xbuf.datas_pb2

from xbuf.datas_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='xbuf/cmds.proto',
  package='xbuf',
  serialized_pb=_b('\n\x0fxbuf/cmds.proto\x12\x04xbuf\x1a\x10xbuf/datas.proto\"\xd9\x01\n\x03\x43md\x12\x1e\n\x06setEye\x18\x02 \x01(\x0b\x32\x0c.xbuf.SetEyeH\x00\x12\x1d\n\x07setData\x18\x03 \x01(\x0b\x32\n.xbuf.DataH\x00\x12&\n\ndeleteData\x18\x04 \x01(\x0b\x32\x10.xbuf.DeleteDataH\x00\x12\x36\n\x12\x63hangeAssetFolders\x18\x05 \x01(\x0b\x32\x18.xbuf.ChangeAssetFoldersH\x00\x12,\n\rplayAnimation\x18\x06 \x01(\x0b\x32\x13.xbuf.PlayAnimationH\x00\x42\x05\n\x03\x63md\"\xea\x01\n\x06SetEye\x12\x1c\n\x08location\x18\x01 \x02(\x0b\x32\n.xbuf.Vec3\x12\"\n\x08rotation\x18\x02 \x02(\x0b\x32\x10.xbuf.Quaternion\x12\x1e\n\nprojection\x18\x03 \x01(\x0b\x32\n.xbuf.Mat4\x12\x0c\n\x04near\x18\x05 \x01(\x02\x12\x0b\n\x03\x66\x61r\x18\x06 \x01(\x02\x12\x34\n\x08projMode\x18\x07 \x01(\x0e\x32\x15.xbuf.SetEye.ProjMode:\x0bperspective\"-\n\x08ProjMode\x12\x0f\n\x0bperspective\x10\x01\x12\x10\n\x0corthographic\x10\x02\"Z\n\x12\x43hangeAssetFolders\x12\x0c\n\x04path\x18\x01 \x03(\t\x12\x16\n\x08register\x18\x02 \x01(\x08:\x04true\x12\x1e\n\x0funregisterOther\x18\x03 \x01(\x08:\x05\x66\x61lse\"Q\n\nDeleteData\x12\x0c\n\x04refs\x18\x01 \x03(\t\x12!\n\trelations\x18\x02 \x03(\x0b\x32\x0e.xbuf.Relation\x12\x12\n\x03\x61ll\x18\x03 \x01(\x08:\x05\x66\x61lse\"5\n\rPlayAnimation\x12\x0b\n\x03ref\x18\x01 \x02(\t\x12\x17\n\x0f\x61nimationsNames\x18\x02 \x03(\tP\x00')
  ,
  dependencies=[xbuf.datas_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_SETEYE_PROJMODE = _descriptor.EnumDescriptor(
  name='ProjMode',
  full_name='xbuf.SetEye.ProjMode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='perspective', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='orthographic', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=453,
  serialized_end=498,
)
_sym_db.RegisterEnumDescriptor(_SETEYE_PROJMODE)


_CMD = _descriptor.Descriptor(
  name='Cmd',
  full_name='xbuf.Cmd',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='setEye', full_name='xbuf.Cmd.setEye', index=0,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='setData', full_name='xbuf.Cmd.setData', index=1,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='deleteData', full_name='xbuf.Cmd.deleteData', index=2,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='changeAssetFolders', full_name='xbuf.Cmd.changeAssetFolders', index=3,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='playAnimation', full_name='xbuf.Cmd.playAnimation', index=4,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='cmd', full_name='xbuf.Cmd.cmd',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=44,
  serialized_end=261,
)


_SETEYE = _descriptor.Descriptor(
  name='SetEye',
  full_name='xbuf.SetEye',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='location', full_name='xbuf.SetEye.location', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rotation', full_name='xbuf.SetEye.rotation', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='projection', full_name='xbuf.SetEye.projection', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='near', full_name='xbuf.SetEye.near', index=3,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='far', full_name='xbuf.SetEye.far', index=4,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='projMode', full_name='xbuf.SetEye.projMode', index=5,
      number=7, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SETEYE_PROJMODE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=264,
  serialized_end=498,
)


_CHANGEASSETFOLDERS = _descriptor.Descriptor(
  name='ChangeAssetFolders',
  full_name='xbuf.ChangeAssetFolders',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='xbuf.ChangeAssetFolders.path', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='register', full_name='xbuf.ChangeAssetFolders.register', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unregisterOther', full_name='xbuf.ChangeAssetFolders.unregisterOther', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=500,
  serialized_end=590,
)


_DELETEDATA = _descriptor.Descriptor(
  name='DeleteData',
  full_name='xbuf.DeleteData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='refs', full_name='xbuf.DeleteData.refs', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='relations', full_name='xbuf.DeleteData.relations', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='all', full_name='xbuf.DeleteData.all', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=592,
  serialized_end=673,
)


_PLAYANIMATION = _descriptor.Descriptor(
  name='PlayAnimation',
  full_name='xbuf.PlayAnimation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ref', full_name='xbuf.PlayAnimation.ref', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='animationsNames', full_name='xbuf.PlayAnimation.animationsNames', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=675,
  serialized_end=728,
)

_CMD.fields_by_name['setEye'].message_type = _SETEYE
_CMD.fields_by_name['setData'].message_type = xbuf.datas_pb2._DATA
_CMD.fields_by_name['deleteData'].message_type = _DELETEDATA
_CMD.fields_by_name['changeAssetFolders'].message_type = _CHANGEASSETFOLDERS
_CMD.fields_by_name['playAnimation'].message_type = _PLAYANIMATION
_CMD.oneofs_by_name['cmd'].fields.append(
  _CMD.fields_by_name['setEye'])
_CMD.fields_by_name['setEye'].containing_oneof = _CMD.oneofs_by_name['cmd']
_CMD.oneofs_by_name['cmd'].fields.append(
  _CMD.fields_by_name['setData'])
_CMD.fields_by_name['setData'].containing_oneof = _CMD.oneofs_by_name['cmd']
_CMD.oneofs_by_name['cmd'].fields.append(
  _CMD.fields_by_name['deleteData'])
_CMD.fields_by_name['deleteData'].containing_oneof = _CMD.oneofs_by_name['cmd']
_CMD.oneofs_by_name['cmd'].fields.append(
  _CMD.fields_by_name['changeAssetFolders'])
_CMD.fields_by_name['changeAssetFolders'].containing_oneof = _CMD.oneofs_by_name['cmd']
_CMD.oneofs_by_name['cmd'].fields.append(
  _CMD.fields_by_name['playAnimation'])
_CMD.fields_by_name['playAnimation'].containing_oneof = _CMD.oneofs_by_name['cmd']
_SETEYE.fields_by_name['location'].message_type = xbuf.datas_pb2._VEC3
_SETEYE.fields_by_name['rotation'].message_type = xbuf.datas_pb2._QUATERNION
_SETEYE.fields_by_name['projection'].message_type = xbuf.datas_pb2._MAT4
_SETEYE.fields_by_name['projMode'].enum_type = _SETEYE_PROJMODE
_SETEYE_PROJMODE.containing_type = _SETEYE
_DELETEDATA.fields_by_name['relations'].message_type = xbuf.datas_pb2._RELATION
DESCRIPTOR.message_types_by_name['Cmd'] = _CMD
DESCRIPTOR.message_types_by_name['SetEye'] = _SETEYE
DESCRIPTOR.message_types_by_name['ChangeAssetFolders'] = _CHANGEASSETFOLDERS
DESCRIPTOR.message_types_by_name['DeleteData'] = _DELETEDATA
DESCRIPTOR.message_types_by_name['PlayAnimation'] = _PLAYANIMATION

Cmd = _reflection.GeneratedProtocolMessageType('Cmd', (_message.Message,), dict(
  DESCRIPTOR = _CMD,
  __module__ = 'xbuf.cmds_pb2'
  # @@protoc_insertion_point(class_scope:xbuf.Cmd)
  ))
_sym_db.RegisterMessage(Cmd)

SetEye = _reflection.GeneratedProtocolMessageType('SetEye', (_message.Message,), dict(
  DESCRIPTOR = _SETEYE,
  __module__ = 'xbuf.cmds_pb2'
  # @@protoc_insertion_point(class_scope:xbuf.SetEye)
  ))
_sym_db.RegisterMessage(SetEye)

ChangeAssetFolders = _reflection.GeneratedProtocolMessageType('ChangeAssetFolders', (_message.Message,), dict(
  DESCRIPTOR = _CHANGEASSETFOLDERS,
  __module__ = 'xbuf.cmds_pb2'
  # @@protoc_insertion_point(class_scope:xbuf.ChangeAssetFolders)
  ))
_sym_db.RegisterMessage(ChangeAssetFolders)

DeleteData = _reflection.GeneratedProtocolMessageType('DeleteData', (_message.Message,), dict(
  DESCRIPTOR = _DELETEDATA,
  __module__ = 'xbuf.cmds_pb2'
  # @@protoc_insertion_point(class_scope:xbuf.DeleteData)
  ))
_sym_db.RegisterMessage(DeleteData)

PlayAnimation = _reflection.GeneratedProtocolMessageType('PlayAnimation', (_message.Message,), dict(
  DESCRIPTOR = _PLAYANIMATION,
  __module__ = 'xbuf.cmds_pb2'
  # @@protoc_insertion_point(class_scope:xbuf.PlayAnimation)
  ))
_sym_db.RegisterMessage(PlayAnimation)


# @@protoc_insertion_point(module_scope)
