# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xbuf/datas.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import xbuf.lights_pb2
import xbuf.materials_pb2
import xbuf.meshes_pb2
import xbuf.primitives_pb2
import xbuf.relations_pb2
import xbuf.skeletons_pb2
import xbuf.tobjects_pb2
import xbuf_ext.animations_kf_pb2
import xbuf_ext.custom_params_pb2

from xbuf.lights_pb2 import *
from xbuf.materials_pb2 import *
from xbuf.meshes_pb2 import *
from xbuf.primitives_pb2 import *
from xbuf.relations_pb2 import *
from xbuf.skeletons_pb2 import *
from xbuf.tobjects_pb2 import *
from xbuf_ext.animations_kf_pb2 import *
from xbuf_ext.custom_params_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='xbuf/datas.proto',
  package='xbuf',
  serialized_pb=_b('\n\x10xbuf/datas.proto\x12\x04xbuf\x1a\x11xbuf/lights.proto\x1a\x14xbuf/materials.proto\x1a\x11xbuf/meshes.proto\x1a\x15xbuf/primitives.proto\x1a\x14xbuf/relations.proto\x1a\x14xbuf/skeletons.proto\x1a\x13xbuf/tobjects.proto\x1a\x1cxbuf_ext/animations_kf.proto\x1a\x1cxbuf_ext/custom_params.proto\"\xce\x02\n\x04\x44\x61ta\x12\x19\n\x07version\x18\x01 \x01(\r:\x08\x32\x30\x31\x35\x30\x39\x31\x34\x12!\n\trelations\x18\x02 \x03(\x0b\x32\x0e.xbuf.Relation\x12\x1f\n\x08tobjects\x18\x03 \x03(\x0b\x32\r.xbuf.TObject\x12!\n\tmaterials\x18\x05 \x03(\x0b\x32\x0e.xbuf.Material\x12\x1b\n\x06lights\x18\x06 \x03(\x0b\x32\x0b.xbuf.Light\x12!\n\tskeletons\x18\x07 \x03(\x0b\x32\x0e.xbuf.Skeleton\x12\x1a\n\x06meshes\x18\x08 \x03(\x0b\x32\n.xbuf.Mesh\x12\x31\n\rcustom_params\x18\xf4\x03 \x03(\x0b\x32\x19.xbuf_ext.CustomParamList\x12-\n\ranimations_kf\x18\xf5\x03 \x03(\x0b\x32\x15.xbuf_ext.AnimationKF*\x06\x08\xa6\x04\x10\xd1\x0fP\x00P\x01P\x02P\x03P\x04P\x05P\x06P\x07P\x08')
  ,
  dependencies=[xbuf.lights_pb2.DESCRIPTOR,xbuf.materials_pb2.DESCRIPTOR,xbuf.meshes_pb2.DESCRIPTOR,xbuf.primitives_pb2.DESCRIPTOR,xbuf.relations_pb2.DESCRIPTOR,xbuf.skeletons_pb2.DESCRIPTOR,xbuf.tobjects_pb2.DESCRIPTOR,xbuf_ext.animations_kf_pb2.DESCRIPTOR,xbuf_ext.custom_params_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DATA = _descriptor.Descriptor(
  name='Data',
  full_name='xbuf.Data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='xbuf.Data.version', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=20150914,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='relations', full_name='xbuf.Data.relations', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tobjects', full_name='xbuf.Data.tobjects', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='materials', full_name='xbuf.Data.materials', index=3,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lights', full_name='xbuf.Data.lights', index=4,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='skeletons', full_name='xbuf.Data.skeletons', index=5,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='meshes', full_name='xbuf.Data.meshes', index=6,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='custom_params', full_name='xbuf.Data.custom_params', index=7,
      number=500, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='animations_kf', full_name='xbuf.Data.animations_kf', index=8,
      number=501, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=True,
  extension_ranges=[(550, 2001), ],
  oneofs=[
  ],
  serialized_start=235,
  serialized_end=569,
)

_DATA.fields_by_name['relations'].message_type = xbuf.relations_pb2._RELATION
_DATA.fields_by_name['tobjects'].message_type = xbuf.tobjects_pb2._TOBJECT
_DATA.fields_by_name['materials'].message_type = xbuf.materials_pb2._MATERIAL
_DATA.fields_by_name['lights'].message_type = xbuf.lights_pb2._LIGHT
_DATA.fields_by_name['skeletons'].message_type = xbuf.skeletons_pb2._SKELETON
_DATA.fields_by_name['meshes'].message_type = xbuf.meshes_pb2._MESH
_DATA.fields_by_name['custom_params'].message_type = xbuf_ext.custom_params_pb2._CUSTOMPARAMLIST
_DATA.fields_by_name['animations_kf'].message_type = xbuf_ext.animations_kf_pb2._ANIMATIONKF
DESCRIPTOR.message_types_by_name['Data'] = _DATA

Data = _reflection.GeneratedProtocolMessageType('Data', (_message.Message,), dict(
  DESCRIPTOR = _DATA,
  __module__ = 'xbuf.datas_pb2'
  # @@protoc_insertion_point(class_scope:xbuf.Data)
  ))
_sym_db.RegisterMessage(Data)


# @@protoc_insertion_point(module_scope)
