# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xbuf/relations.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='xbuf/relations.proto',
  package='xbuf',
  syntax='proto3',
  serialized_pb=_b('\n\x14xbuf/relations.proto\x12\x04xbuf\"5\n\x08Relation\x12\x0c\n\x04ref1\x18\x01 \x01(\t\x12\x0c\n\x04ref2\x18\x02 \x01(\t\x12\r\n\x05label\x18\x03 \x01(\tb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_RELATION = _descriptor.Descriptor(
  name='Relation',
  full_name='xbuf.Relation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ref1', full_name='xbuf.Relation.ref1', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ref2', full_name='xbuf.Relation.ref2', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='label', full_name='xbuf.Relation.label', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=83,
)

DESCRIPTOR.message_types_by_name['Relation'] = _RELATION

Relation = _reflection.GeneratedProtocolMessageType('Relation', (_message.Message,), dict(
  DESCRIPTOR = _RELATION,
  __module__ = 'xbuf.relations_pb2'
  # @@protoc_insertion_point(class_scope:xbuf.Relation)
  ))
_sym_db.RegisterMessage(Relation)


# @@protoc_insertion_point(module_scope)
