# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xbuf/skeletons.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from xbuf import primitives_pb2 as xbuf_dot_primitives__pb2
from xbuf import relations_pb2 as xbuf_dot_relations__pb2

from xbuf.primitives_pb2 import *
from xbuf.relations_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='xbuf/skeletons.proto',
  package='xbuf',
  syntax='proto3',
  serialized_pb=_b('\n\x14xbuf/skeletons.proto\x12\x04xbuf\x1a\x15xbuf/primitives.proto\x1a\x14xbuf/relations.proto\"d\n\x08Skeleton\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x19\n\x05\x62ones\x18\x03 \x03(\x0b\x32\n.xbuf.Bone\x12#\n\x0b\x62ones_graph\x18\x04 \x03(\x0b\x32\x0e.xbuf.Relation\"D\n\x04\x42one\x12\n\n\x02id\x18\x01 \x01(\t\x12\"\n\ttransform\x18\x02 \x01(\x0b\x32\x0f.xbuf.Transform\x12\x0c\n\x04name\x18\x04 \x01(\tP\x00P\x01\x62\x06proto3')
  ,
  dependencies=[xbuf_dot_primitives__pb2.DESCRIPTOR,xbuf_dot_relations__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SKELETON = _descriptor.Descriptor(
  name='Skeleton',
  full_name='xbuf.Skeleton',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='xbuf.Skeleton.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='xbuf.Skeleton.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bones', full_name='xbuf.Skeleton.bones', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bones_graph', full_name='xbuf.Skeleton.bones_graph', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=175,
)


_BONE = _descriptor.Descriptor(
  name='Bone',
  full_name='xbuf.Bone',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='xbuf.Bone.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='transform', full_name='xbuf.Bone.transform', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='xbuf.Bone.name', index=2,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=177,
  serialized_end=245,
)

_SKELETON.fields_by_name['bones'].message_type = _BONE
_SKELETON.fields_by_name['bones_graph'].message_type = xbuf_dot_relations__pb2._RELATION
_BONE.fields_by_name['transform'].message_type = xbuf_dot_primitives__pb2._TRANSFORM
DESCRIPTOR.message_types_by_name['Skeleton'] = _SKELETON
DESCRIPTOR.message_types_by_name['Bone'] = _BONE

Skeleton = _reflection.GeneratedProtocolMessageType('Skeleton', (_message.Message,), dict(
  DESCRIPTOR = _SKELETON,
  __module__ = 'xbuf.skeletons_pb2'
  # @@protoc_insertion_point(class_scope:xbuf.Skeleton)
  ))
_sym_db.RegisterMessage(Skeleton)

Bone = _reflection.GeneratedProtocolMessageType('Bone', (_message.Message,), dict(
  DESCRIPTOR = _BONE,
  __module__ = 'xbuf.skeletons_pb2'
  # @@protoc_insertion_point(class_scope:xbuf.Bone)
  ))
_sym_db.RegisterMessage(Bone)


# @@protoc_insertion_point(module_scope)
