# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xbuf_ext/animations_kf.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='xbuf_ext/animations_kf.proto',
  package='xbuf_ext',
  serialized_pb=_b('\n\x1cxbuf_ext/animations_kf.proto\x12\x08xbuf_ext\"\xc1\x01\n\x0b\x41nimationKF\x12\n\n\x02id\x18\x01 \x02(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08\x64uration\x18\x03 \x01(\x05\x12\x1d\n\x05\x63lips\x18\x04 \x03(\x0b\x32\x0e.xbuf_ext.Clip\x12>\n\x0btarget_kind\x18\x05 \x01(\x0e\x32 .xbuf_ext.AnimationKF.TargetKind:\x07tobject\"\'\n\nTargetKind\x12\x0b\n\x07tobject\x10\x00\x12\x0c\n\x08skeleton\x10\x01\"L\n\x04\x43lip\x12\x37\n\x11sampled_transform\x18\x01 \x01(\x0b\x32\x1a.xbuf_ext.SampledTransformH\x00\x42\x0b\n\tkeyframes\"\xa5\x02\n\x10SampledTransform\x12\x0e\n\x02\x61t\x18\x01 \x03(\x05\x42\x02\x10\x01\x12\x19\n\rtranslation_x\x18\x02 \x03(\x02\x42\x02\x10\x01\x12\x19\n\rtranslation_y\x18\x03 \x03(\x02\x42\x02\x10\x01\x12\x19\n\rtranslation_z\x18\x04 \x03(\x02\x42\x02\x10\x01\x12\x16\n\nrotation_x\x18\x05 \x03(\x02\x42\x02\x10\x01\x12\x16\n\nrotation_y\x18\x06 \x03(\x02\x42\x02\x10\x01\x12\x16\n\nrotation_z\x18\x07 \x03(\x02\x42\x02\x10\x01\x12\x16\n\nrotation_w\x18\x08 \x03(\x02\x42\x02\x10\x01\x12\x13\n\x07scale_x\x18\t \x03(\x02\x42\x02\x10\x01\x12\x13\n\x07scale_y\x18\n \x03(\x02\x42\x02\x10\x01\x12\x13\n\x07scale_z\x18\x0b \x03(\x02\x42\x02\x10\x01\x12\x11\n\tbone_name\x18\x14 \x01(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_ANIMATIONKF_TARGETKIND = _descriptor.EnumDescriptor(
  name='TargetKind',
  full_name='xbuf_ext.AnimationKF.TargetKind',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='tobject', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='skeleton', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=197,
  serialized_end=236,
)
_sym_db.RegisterEnumDescriptor(_ANIMATIONKF_TARGETKIND)


_ANIMATIONKF = _descriptor.Descriptor(
  name='AnimationKF',
  full_name='xbuf_ext.AnimationKF',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='xbuf_ext.AnimationKF.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='xbuf_ext.AnimationKF.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='duration', full_name='xbuf_ext.AnimationKF.duration', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='clips', full_name='xbuf_ext.AnimationKF.clips', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='target_kind', full_name='xbuf_ext.AnimationKF.target_kind', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ANIMATIONKF_TARGETKIND,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=236,
)


_CLIP = _descriptor.Descriptor(
  name='Clip',
  full_name='xbuf_ext.Clip',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sampled_transform', full_name='xbuf_ext.Clip.sampled_transform', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='keyframes', full_name='xbuf_ext.Clip.keyframes',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=238,
  serialized_end=314,
)


_SAMPLEDTRANSFORM = _descriptor.Descriptor(
  name='SampledTransform',
  full_name='xbuf_ext.SampledTransform',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='at', full_name='xbuf_ext.SampledTransform.at', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
    _descriptor.FieldDescriptor(
      name='translation_x', full_name='xbuf_ext.SampledTransform.translation_x', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
    _descriptor.FieldDescriptor(
      name='translation_y', full_name='xbuf_ext.SampledTransform.translation_y', index=2,
      number=3, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
    _descriptor.FieldDescriptor(
      name='translation_z', full_name='xbuf_ext.SampledTransform.translation_z', index=3,
      number=4, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
    _descriptor.FieldDescriptor(
      name='rotation_x', full_name='xbuf_ext.SampledTransform.rotation_x', index=4,
      number=5, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
    _descriptor.FieldDescriptor(
      name='rotation_y', full_name='xbuf_ext.SampledTransform.rotation_y', index=5,
      number=6, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
    _descriptor.FieldDescriptor(
      name='rotation_z', full_name='xbuf_ext.SampledTransform.rotation_z', index=6,
      number=7, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
    _descriptor.FieldDescriptor(
      name='rotation_w', full_name='xbuf_ext.SampledTransform.rotation_w', index=7,
      number=8, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
    _descriptor.FieldDescriptor(
      name='scale_x', full_name='xbuf_ext.SampledTransform.scale_x', index=8,
      number=9, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
    _descriptor.FieldDescriptor(
      name='scale_y', full_name='xbuf_ext.SampledTransform.scale_y', index=9,
      number=10, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
    _descriptor.FieldDescriptor(
      name='scale_z', full_name='xbuf_ext.SampledTransform.scale_z', index=10,
      number=11, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
    _descriptor.FieldDescriptor(
      name='bone_name', full_name='xbuf_ext.SampledTransform.bone_name', index=11,
      number=20, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=317,
  serialized_end=610,
)

_ANIMATIONKF.fields_by_name['clips'].message_type = _CLIP
_ANIMATIONKF.fields_by_name['target_kind'].enum_type = _ANIMATIONKF_TARGETKIND
_ANIMATIONKF_TARGETKIND.containing_type = _ANIMATIONKF
_CLIP.fields_by_name['sampled_transform'].message_type = _SAMPLEDTRANSFORM
_CLIP.oneofs_by_name['keyframes'].fields.append(
  _CLIP.fields_by_name['sampled_transform'])
_CLIP.fields_by_name['sampled_transform'].containing_oneof = _CLIP.oneofs_by_name['keyframes']
DESCRIPTOR.message_types_by_name['AnimationKF'] = _ANIMATIONKF
DESCRIPTOR.message_types_by_name['Clip'] = _CLIP
DESCRIPTOR.message_types_by_name['SampledTransform'] = _SAMPLEDTRANSFORM

AnimationKF = _reflection.GeneratedProtocolMessageType('AnimationKF', (_message.Message,), dict(
  DESCRIPTOR = _ANIMATIONKF,
  __module__ = 'xbuf_ext.animations_kf_pb2'
  # @@protoc_insertion_point(class_scope:xbuf_ext.AnimationKF)
  ))
_sym_db.RegisterMessage(AnimationKF)

Clip = _reflection.GeneratedProtocolMessageType('Clip', (_message.Message,), dict(
  DESCRIPTOR = _CLIP,
  __module__ = 'xbuf_ext.animations_kf_pb2'
  # @@protoc_insertion_point(class_scope:xbuf_ext.Clip)
  ))
_sym_db.RegisterMessage(Clip)

SampledTransform = _reflection.GeneratedProtocolMessageType('SampledTransform', (_message.Message,), dict(
  DESCRIPTOR = _SAMPLEDTRANSFORM,
  __module__ = 'xbuf_ext.animations_kf_pb2'
  # @@protoc_insertion_point(class_scope:xbuf_ext.SampledTransform)
  ))
_sym_db.RegisterMessage(SampledTransform)


_SAMPLEDTRANSFORM.fields_by_name['at'].has_options = True
_SAMPLEDTRANSFORM.fields_by_name['at']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
_SAMPLEDTRANSFORM.fields_by_name['translation_x'].has_options = True
_SAMPLEDTRANSFORM.fields_by_name['translation_x']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
_SAMPLEDTRANSFORM.fields_by_name['translation_y'].has_options = True
_SAMPLEDTRANSFORM.fields_by_name['translation_y']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
_SAMPLEDTRANSFORM.fields_by_name['translation_z'].has_options = True
_SAMPLEDTRANSFORM.fields_by_name['translation_z']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
_SAMPLEDTRANSFORM.fields_by_name['rotation_x'].has_options = True
_SAMPLEDTRANSFORM.fields_by_name['rotation_x']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
_SAMPLEDTRANSFORM.fields_by_name['rotation_y'].has_options = True
_SAMPLEDTRANSFORM.fields_by_name['rotation_y']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
_SAMPLEDTRANSFORM.fields_by_name['rotation_z'].has_options = True
_SAMPLEDTRANSFORM.fields_by_name['rotation_z']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
_SAMPLEDTRANSFORM.fields_by_name['rotation_w'].has_options = True
_SAMPLEDTRANSFORM.fields_by_name['rotation_w']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
_SAMPLEDTRANSFORM.fields_by_name['scale_x'].has_options = True
_SAMPLEDTRANSFORM.fields_by_name['scale_x']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
_SAMPLEDTRANSFORM.fields_by_name['scale_y'].has_options = True
_SAMPLEDTRANSFORM.fields_by_name['scale_y']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
_SAMPLEDTRANSFORM.fields_by_name['scale_z'].has_options = True
_SAMPLEDTRANSFORM.fields_by_name['scale_z']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
# @@protoc_insertion_point(module_scope)
