# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xbuf_ext/custom_params.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import xbuf.datas_pb2

from xbuf.datas_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='xbuf_ext/custom_params.proto',
  package='xbuf_ext',
  serialized_pb=_b('\n\x1cxbuf_ext/custom_params.proto\x12\x08xbuf_ext\x1a\x10xbuf/datas.proto\"D\n\x0f\x43ustomParamList\x12\n\n\x02id\x18\x01 \x02(\t\x12%\n\x06params\x18\x02 \x03(\x0b\x32\x15.xbuf_ext.CustomParam\"\xc3\x02\n\x0b\x43ustomParam\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x0f\n\x05vbool\x18\x02 \x01(\x08H\x00\x12\x11\n\x07vstring\x18\x03 \x01(\tH\x00\x12\x10\n\x06vfloat\x18\x04 \x01(\x02H\x00\x12\x0e\n\x04vint\x18\x05 \x01(\x05H\x00\x12\x1b\n\x05vvec2\x18\n \x01(\x0b\x32\n.xbuf.Vec2H\x00\x12\x1b\n\x05vvec3\x18\x0b \x01(\x0b\x32\n.xbuf.Vec3H\x00\x12\x1b\n\x05vvec4\x18\x0c \x01(\x0b\x32\n.xbuf.Vec4H\x00\x12!\n\x05vquat\x18\r \x01(\x0b\x32\x10.xbuf.QuaternionH\x00\x12\x1b\n\x05vmat4\x18\x0e \x01(\x0b\x32\n.xbuf.Mat4H\x00\x12!\n\x08vtexture\x18\x0f \x01(\x0b\x32\r.xbuf.TextureH\x00\x12\x1d\n\x06vcolor\x18\x10 \x01(\x0b\x32\x0b.xbuf.ColorH\x00\x42\x07\n\x05value:=\n\rcustom_params\x12\n.xbuf.Data\x18\xf4\x03 \x03(\x0b\x32\x19.xbuf_ext.CustomParamListP\x00')
  ,
  dependencies=[xbuf.datas_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


CUSTOM_PARAMS_FIELD_NUMBER = 500
custom_params = _descriptor.FieldDescriptor(
  name='custom_params', full_name='xbuf_ext.custom_params', index=0,
  number=500, type=11, cpp_type=10, label=3,
  has_default_value=False, default_value=[],
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)


_CUSTOMPARAMLIST = _descriptor.Descriptor(
  name='CustomParamList',
  full_name='xbuf_ext.CustomParamList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='xbuf_ext.CustomParamList.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='params', full_name='xbuf_ext.CustomParamList.params', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=128,
)


_CUSTOMPARAM = _descriptor.Descriptor(
  name='CustomParam',
  full_name='xbuf_ext.CustomParam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='xbuf_ext.CustomParam.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vbool', full_name='xbuf_ext.CustomParam.vbool', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vstring', full_name='xbuf_ext.CustomParam.vstring', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vfloat', full_name='xbuf_ext.CustomParam.vfloat', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vint', full_name='xbuf_ext.CustomParam.vint', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vvec2', full_name='xbuf_ext.CustomParam.vvec2', index=5,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vvec3', full_name='xbuf_ext.CustomParam.vvec3', index=6,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vvec4', full_name='xbuf_ext.CustomParam.vvec4', index=7,
      number=12, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vquat', full_name='xbuf_ext.CustomParam.vquat', index=8,
      number=13, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vmat4', full_name='xbuf_ext.CustomParam.vmat4', index=9,
      number=14, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vtexture', full_name='xbuf_ext.CustomParam.vtexture', index=10,
      number=15, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vcolor', full_name='xbuf_ext.CustomParam.vcolor', index=11,
      number=16, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='value', full_name='xbuf_ext.CustomParam.value',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=131,
  serialized_end=454,
)

_CUSTOMPARAMLIST.fields_by_name['params'].message_type = _CUSTOMPARAM
_CUSTOMPARAM.fields_by_name['vvec2'].message_type = xbuf.datas_pb2._VEC2
_CUSTOMPARAM.fields_by_name['vvec3'].message_type = xbuf.datas_pb2._VEC3
_CUSTOMPARAM.fields_by_name['vvec4'].message_type = xbuf.datas_pb2._VEC4
_CUSTOMPARAM.fields_by_name['vquat'].message_type = xbuf.datas_pb2._QUATERNION
_CUSTOMPARAM.fields_by_name['vmat4'].message_type = xbuf.datas_pb2._MAT4
_CUSTOMPARAM.fields_by_name['vtexture'].message_type = xbuf.datas_pb2._TEXTURE
_CUSTOMPARAM.fields_by_name['vcolor'].message_type = xbuf.datas_pb2._COLOR
_CUSTOMPARAM.oneofs_by_name['value'].fields.append(
  _CUSTOMPARAM.fields_by_name['vbool'])
_CUSTOMPARAM.fields_by_name['vbool'].containing_oneof = _CUSTOMPARAM.oneofs_by_name['value']
_CUSTOMPARAM.oneofs_by_name['value'].fields.append(
  _CUSTOMPARAM.fields_by_name['vstring'])
_CUSTOMPARAM.fields_by_name['vstring'].containing_oneof = _CUSTOMPARAM.oneofs_by_name['value']
_CUSTOMPARAM.oneofs_by_name['value'].fields.append(
  _CUSTOMPARAM.fields_by_name['vfloat'])
_CUSTOMPARAM.fields_by_name['vfloat'].containing_oneof = _CUSTOMPARAM.oneofs_by_name['value']
_CUSTOMPARAM.oneofs_by_name['value'].fields.append(
  _CUSTOMPARAM.fields_by_name['vint'])
_CUSTOMPARAM.fields_by_name['vint'].containing_oneof = _CUSTOMPARAM.oneofs_by_name['value']
_CUSTOMPARAM.oneofs_by_name['value'].fields.append(
  _CUSTOMPARAM.fields_by_name['vvec2'])
_CUSTOMPARAM.fields_by_name['vvec2'].containing_oneof = _CUSTOMPARAM.oneofs_by_name['value']
_CUSTOMPARAM.oneofs_by_name['value'].fields.append(
  _CUSTOMPARAM.fields_by_name['vvec3'])
_CUSTOMPARAM.fields_by_name['vvec3'].containing_oneof = _CUSTOMPARAM.oneofs_by_name['value']
_CUSTOMPARAM.oneofs_by_name['value'].fields.append(
  _CUSTOMPARAM.fields_by_name['vvec4'])
_CUSTOMPARAM.fields_by_name['vvec4'].containing_oneof = _CUSTOMPARAM.oneofs_by_name['value']
_CUSTOMPARAM.oneofs_by_name['value'].fields.append(
  _CUSTOMPARAM.fields_by_name['vquat'])
_CUSTOMPARAM.fields_by_name['vquat'].containing_oneof = _CUSTOMPARAM.oneofs_by_name['value']
_CUSTOMPARAM.oneofs_by_name['value'].fields.append(
  _CUSTOMPARAM.fields_by_name['vmat4'])
_CUSTOMPARAM.fields_by_name['vmat4'].containing_oneof = _CUSTOMPARAM.oneofs_by_name['value']
_CUSTOMPARAM.oneofs_by_name['value'].fields.append(
  _CUSTOMPARAM.fields_by_name['vtexture'])
_CUSTOMPARAM.fields_by_name['vtexture'].containing_oneof = _CUSTOMPARAM.oneofs_by_name['value']
_CUSTOMPARAM.oneofs_by_name['value'].fields.append(
  _CUSTOMPARAM.fields_by_name['vcolor'])
_CUSTOMPARAM.fields_by_name['vcolor'].containing_oneof = _CUSTOMPARAM.oneofs_by_name['value']
DESCRIPTOR.message_types_by_name['CustomParamList'] = _CUSTOMPARAMLIST
DESCRIPTOR.message_types_by_name['CustomParam'] = _CUSTOMPARAM
DESCRIPTOR.extensions_by_name['custom_params'] = custom_params

CustomParamList = _reflection.GeneratedProtocolMessageType('CustomParamList', (_message.Message,), dict(
  DESCRIPTOR = _CUSTOMPARAMLIST,
  __module__ = 'xbuf_ext.custom_params_pb2'
  # @@protoc_insertion_point(class_scope:xbuf_ext.CustomParamList)
  ))
_sym_db.RegisterMessage(CustomParamList)

CustomParam = _reflection.GeneratedProtocolMessageType('CustomParam', (_message.Message,), dict(
  DESCRIPTOR = _CUSTOMPARAM,
  __module__ = 'xbuf_ext.custom_params_pb2'
  # @@protoc_insertion_point(class_scope:xbuf_ext.CustomParam)
  ))
_sym_db.RegisterMessage(CustomParam)

custom_params.message_type = _CUSTOMPARAMLIST
xbuf.datas_pb2.Data.RegisterExtension(custom_params)

# @@protoc_insertion_point(module_scope)
