# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pgex/cmds.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import pgex.datas_pb2

from pgex.datas_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='pgex/cmds.proto',
  package='pgex',
  serialized_pb=_b('\n\x0fpgex/cmds.proto\x12\x04pgex\x1a\x10pgex/datas.proto\"l\n\x03\x43md\x12\x1e\n\x06setEye\x18\x02 \x01(\x0b\x32\x0c.pgex.SetEyeH\x00\x12\x1d\n\x07setData\x18\x03 \x01(\x0b\x32\n.pgex.DataH\x00\x12\x1f\n\tunsetData\x18\x04 \x01(\x0b\x32\n.pgex.DataH\x00\x42\x05\n\x03\x63md\"\x85\x01\n\x06SetEye\x12\x1c\n\x08location\x18\x01 \x02(\x0b\x32\n.pgex.Vec3\x12\"\n\x08rotation\x18\x02 \x02(\x0b\x32\x10.pgex.Quaternion\x12\x1e\n\nprojection\x18\x03 \x01(\x0b\x32\n.pgex.Mat4\x12\x0c\n\x04near\x18\x05 \x01(\x02\x12\x0b\n\x03\x66\x61r\x18\x06 \x01(\x02\x42\x02H\x03P\x00')
  ,
  dependencies=[pgex.datas_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CMD = _descriptor.Descriptor(
  name='Cmd',
  full_name='pgex.Cmd',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='setEye', full_name='pgex.Cmd.setEye', index=0,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='setData', full_name='pgex.Cmd.setData', index=1,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unsetData', full_name='pgex.Cmd.unsetData', index=2,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='cmd', full_name='pgex.Cmd.cmd',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=43,
  serialized_end=151,
)


_SETEYE = _descriptor.Descriptor(
  name='SetEye',
  full_name='pgex.SetEye',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='location', full_name='pgex.SetEye.location', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rotation', full_name='pgex.SetEye.rotation', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='projection', full_name='pgex.SetEye.projection', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='near', full_name='pgex.SetEye.near', index=3,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='far', full_name='pgex.SetEye.far', index=4,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=154,
  serialized_end=287,
)

_CMD.fields_by_name['setEye'].message_type = _SETEYE
_CMD.fields_by_name['setData'].message_type = pgex.datas_pb2._DATA
_CMD.fields_by_name['unsetData'].message_type = pgex.datas_pb2._DATA
_CMD.oneofs_by_name['cmd'].fields.append(
  _CMD.fields_by_name['setEye'])
_CMD.fields_by_name['setEye'].containing_oneof = _CMD.oneofs_by_name['cmd']
_CMD.oneofs_by_name['cmd'].fields.append(
  _CMD.fields_by_name['setData'])
_CMD.fields_by_name['setData'].containing_oneof = _CMD.oneofs_by_name['cmd']
_CMD.oneofs_by_name['cmd'].fields.append(
  _CMD.fields_by_name['unsetData'])
_CMD.fields_by_name['unsetData'].containing_oneof = _CMD.oneofs_by_name['cmd']
_SETEYE.fields_by_name['location'].message_type = pgex.datas_pb2._VEC3
_SETEYE.fields_by_name['rotation'].message_type = pgex.datas_pb2._QUATERNION
_SETEYE.fields_by_name['projection'].message_type = pgex.datas_pb2._MAT4
DESCRIPTOR.message_types_by_name['Cmd'] = _CMD
DESCRIPTOR.message_types_by_name['SetEye'] = _SETEYE

Cmd = _reflection.GeneratedProtocolMessageType('Cmd', (_message.Message,), dict(
  DESCRIPTOR = _CMD,
  __module__ = 'pgex.cmds_pb2'
  # @@protoc_insertion_point(class_scope:pgex.Cmd)
  ))
_sym_db.RegisterMessage(Cmd)

SetEye = _reflection.GeneratedProtocolMessageType('SetEye', (_message.Message,), dict(
  DESCRIPTOR = _SETEYE,
  __module__ = 'pgex.cmds_pb2'
  # @@protoc_insertion_point(class_scope:pgex.SetEye)
  ))
_sym_db.RegisterMessage(SetEye)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('H\003'))
# @@protoc_insertion_point(module_scope)
