# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cmds.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pgex import math_pb2

from pgex.math_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='cmds.proto',
  package='pgex',
  serialized_pb=_b('\n\ncmds.proto\x12\x04pgex\x1a\nmath.proto\"2\n\x03\x43md\x12$\n\tsetCamera\x18\x01 \x01(\x0b\x32\x0f.pgex.SetCameraH\x00\x42\x05\n\x03\x63md\"m\n\tSetCamera\x12\x1c\n\x08location\x18\x01 \x02(\x0b\x32\n.pgex.Vec3\x12\"\n\x08rotation\x18\x02 \x02(\x0b\x32\x10.pgex.Quaternion\x12\x1e\n\nprojection\x18\x03 \x02(\x0b\x32\n.pgex.Mat4B\x02H\x03P\x00')
  ,
  dependencies=[math_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CMD = _descriptor.Descriptor(
  name='Cmd',
  full_name='pgex.Cmd',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='setCamera', full_name='pgex.Cmd.setCamera', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='cmd', full_name='pgex.Cmd.cmd',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=32,
  serialized_end=82,
)


_SETCAMERA = _descriptor.Descriptor(
  name='SetCamera',
  full_name='pgex.SetCamera',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='location', full_name='pgex.SetCamera.location', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rotation', full_name='pgex.SetCamera.rotation', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='projection', full_name='pgex.SetCamera.projection', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=193,
)

_CMD.fields_by_name['setCamera'].message_type = _SETCAMERA
_CMD.oneofs_by_name['cmd'].fields.append(
  _CMD.fields_by_name['setCamera'])
_CMD.fields_by_name['setCamera'].containing_oneof = _CMD.oneofs_by_name['cmd']
_SETCAMERA.fields_by_name['location'].message_type = math_pb2._VEC3
_SETCAMERA.fields_by_name['rotation'].message_type = math_pb2._QUATERNION
_SETCAMERA.fields_by_name['projection'].message_type = math_pb2._MAT4
DESCRIPTOR.message_types_by_name['Cmd'] = _CMD
DESCRIPTOR.message_types_by_name['SetCamera'] = _SETCAMERA

Cmd = _reflection.GeneratedProtocolMessageType('Cmd', (_message.Message,), dict(
  DESCRIPTOR = _CMD,
  __module__ = 'cmds_pb2'
  # @@protoc_insertion_point(class_scope:pgex.Cmd)
  ))
_sym_db.RegisterMessage(Cmd)

SetCamera = _reflection.GeneratedProtocolMessageType('SetCamera', (_message.Message,), dict(
  DESCRIPTOR = _SETCAMERA,
  __module__ = 'cmds_pb2'
  # @@protoc_insertion_point(class_scope:pgex.SetCamera)
  ))
_sym_db.RegisterMessage(SetCamera)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('H\003'))
# @@protoc_insertion_point(module_scope)
